spring:
  application:
    name: franchise-management-api

  r2dbc:
    url: r2dbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret

  docker:
    compose:
      enabled: true

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8080
